#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
    rt_entry_t* ret = NULL;
    u32 match_num = 0;
	rt_entry_t *entry = NULL;
	list_for_each_entry(entry, &rtable, list) {
		fprintf(stdout, IP_FMT"\t"IP_FMT"\t"IP_FMT"\t%s\n", \
				HOST_IP_FMT_STR(entry->dest), \
				HOST_IP_FMT_STR(entry->mask), \
				HOST_IP_FMT_STR(entry->gw), \
				entry->if_name);
        u32 masked_ip = entry->mask & entry->dest; 
        u32 masked_dst_ip = entry->mask & dst;
        if(masked_ip == masked_dst_ip && masked_dst_ip > match_num) {
            ret = entry;
            match_num = masked_dst_ip;
        }
	}

    return ret;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(iface_info_t *iface, char *packet, int len)
{
    icmphdr_t* p = (icmphdr_t*)packet;
    iphdr_t* payload = (iphdr_t*)((void*)p + ICMP_HDR_SIZE);
    iface_send_packet_by_arp(iface, payload->saddr, packet, len);
}
